spring.application.name=ms-profissionais
server.port=8081

# conexao
spring.datasource.url=${DB_URL:jdbc:mysql://35.199.95.124:3306/gsw_database}
spring.datasource.username=${DB_USERNAME:chronosapi}
spring.datasource.password=${DB_PASSWORD:Bolsonaro#22}

# comando
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

